import type { PredictionMarket } from "@/generated/prisma/enums";

export type MarketFilter =
  | { type: "market"; markets: PredictionMarket[] }
  | { type: "oddsRange"; min: number; max: number }
  | { type: "all" }
  | { type: "banker" }
  | { type: "topConfidence"; minConfidence: number };

export type MarketPageConfig = {
  slug: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  filter: MarketFilter;
};

export const MARKET_PAGES: MarketPageConfig[] = [
  {
    slug: "1x2",
    h1: "1X2 Predictions",
    metaTitle: "1X2 Match Result Predictions Today",
    metaDescription: "Today's 1X2 (match result) tips - Home Win, Draw, or Away Win - generated by our statistical model.",
    intro: "The classic match result market: 1 for Home Win, X for Draw, 2 for Away Win.",
    filter: { type: "market", markets: ["HOME_WIN", "DRAW", "AWAY_WIN"] },
  },
  {
    slug: "over-1-5-goals",
    h1: "Over 1.5 Goals Predictions",
    metaTitle: "Over 1.5 Goals Predictions Today",
    metaDescription: "Today's Over 1.5 goals tips, generated by our statistical model and reviewed for confidence.",
    intro: "Fixtures where our model expects at least two goals, based on both teams' scoring and conceding form.",
    filter: { type: "market", markets: ["OVER_1_5"] },
  },
  {
    slug: "over-2-5-goals",
    h1: "Over 2.5 Goals Predictions",
    metaTitle: "Over 2.5 Goals Predictions Today",
    metaDescription: "Today's Over 2.5 goals tips, generated by our statistical model and reviewed for confidence.",
    intro: "Fixtures where our model expects three or more goals, based on both teams' scoring and conceding form.",
    filter: { type: "market", markets: ["OVER_2_5"] },
  },
  {
    slug: "under-3-5-goals",
    h1: "Under 3.5 Goals Predictions",
    metaTitle: "Under 3.5 Goals Predictions Today",
    metaDescription: "Today's Under 3.5 goals tips, generated by our statistical model and reviewed for confidence.",
    intro: "Fixtures our model expects to stay under four total goals.",
    filter: { type: "market", markets: ["UNDER_3_5"] },
  },
  {
    slug: "both-teams-to-score",
    h1: "Both Teams to Score Predictions",
    metaTitle: "BTTS Predictions Today",
    metaDescription: "Today's Both Teams to Score (BTTS) tips, generated by our statistical model.",
    intro: "Fixtures where our model favors both sides finding the net.",
    filter: { type: "market", markets: ["BTTS_YES", "BTTS_NO"] },
  },
  {
    slug: "double-chance",
    h1: "Double Chance Predictions",
    metaTitle: "Double Chance Predictions Today",
    metaDescription: "Today's Double Chance tips (1X, X2, 12), generated by our statistical model.",
    intro: "A safer market covering two of the three possible results in one bet.",
    filter: { type: "market", markets: ["DOUBLE_CHANCE_1X", "DOUBLE_CHANCE_X2", "DOUBLE_CHANCE_12"] },
  },
  {
    slug: "draw-no-bet",
    h1: "Draw No Bet Predictions",
    metaTitle: "Draw No Bet Predictions Today",
    metaDescription: "Today's Draw No Bet tips, generated by our statistical model.",
    intro: "Back a side to win with your stake refunded if the match ends level.",
    filter: { type: "market", markets: ["DRAW_NO_BET_HOME", "DRAW_NO_BET_AWAY"] },
  },
  {
    slug: "correct-score",
    h1: "Correct Score Predictions",
    metaTitle: "Correct Score Predictions Today",
    metaDescription: "Today's Correct Score tips - the model's highest-probability final scoreline per fixture.",
    intro: "Higher risk, higher reward - the single most likely final score from our score matrix.",
    filter: { type: "market", markets: ["CORRECT_SCORE"] },
  },
  {
    slug: "home-wins",
    h1: "Home Win Predictions",
    metaTitle: "Home Win Predictions Today",
    metaDescription: "Today's Home Win tips, generated by our statistical model.",
    intro: "Fixtures our model favors the home side to win outright.",
    filter: { type: "market", markets: ["HOME_WIN"] },
  },
  {
    slug: "away-wins",
    h1: "Away Win Predictions",
    metaTitle: "Away Win Predictions Today",
    metaDescription: "Today's Away Win tips, generated by our statistical model.",
    intro: "Fixtures our model favors the away side to win outright.",
    filter: { type: "market", markets: ["AWAY_WIN"] },
  },
  {
    slug: "draws",
    h1: "Draw Predictions",
    metaTitle: "Draw Predictions Today",
    metaDescription: "Today's Draw tips, generated by our statistical model.",
    intro: "Fixtures our model rates as more likely than not to end level.",
    filter: { type: "market", markets: ["DRAW"] },
  },
  {
    slug: "win-either-half",
    h1: "Over 0.5 Goals in the First Half",
    metaTitle: "First Half Goals Predictions Today",
    metaDescription: "Today's first-half goals tips - fixtures our model expects to see a goal before half-time.",
    intro:
      "Our model doesn't yet price a dedicated \"win either half\" market, so this page shows the closest thing it does model: a goal scored before half-time.",
    filter: { type: "market", markets: ["HT_OVER_0_5"] },
  },
  {
    slug: "single-bets",
    h1: "Today's Single Bets",
    metaTitle: "Single Bet Predictions Today",
    metaDescription: "Every standalone tip published today, across all markets.",
    intro: "Every tip our model has published today, one match at a time - no accumulators.",
    filter: { type: "all" },
  },
  {
    slug: "banker-of-the-day",
    h1: "Banker of the Day",
    metaTitle: "Banker of the Day Predictions",
    metaDescription: "Our highest-confidence single tip each day.",
    intro: "The single pick our model is most confident in, one per day. Confidence is capped at 92% - nothing is guaranteed.",
    filter: { type: "banker" },
  },
  {
    slug: "2-odds",
    h1: "2 Odds Predictions",
    metaTitle: "2 Odds Predictions Today",
    metaDescription: "Today's tips priced around 2.00 odds.",
    intro: "Published tips with derived odds between 1.80 and 2.20.",
    filter: { type: "oddsRange", min: 1.8, max: 2.2 },
  },
  {
    slug: "3-odds",
    h1: "3 Odds Predictions",
    metaTitle: "3 Odds Predictions Today",
    metaDescription: "Today's tips priced around 3.00 odds.",
    intro: "Published tips with derived odds between 2.5 and 3.5.",
    filter: { type: "oddsRange", min: 2.5, max: 3.5 },
  },
  {
    slug: "5-odds",
    h1: "5 Odds Predictions",
    metaTitle: "5 Odds Predictions Today",
    metaDescription: "Today's tips priced around 5.00 odds.",
    intro: "Published tips with derived odds between 4.0 and 6.0.",
    filter: { type: "oddsRange", min: 4.0, max: 6.0 },
  },
  {
    slug: "acca-tips",
    h1: "Accumulator Tips",
    metaTitle: "Acca Tips Today",
    metaDescription: "Today's highest-confidence tips, suggested as accumulator legs.",
    intro: "Today's tips at 80% confidence or higher - a starting point for building your own accumulator. Combining selections multiplies risk, not just returns.",
    filter: { type: "topConfidence", minConfidence: 80 },
  },
];

export function getMarketPageConfig(slug: string): MarketPageConfig | undefined {
  return MARKET_PAGES.find((m) => m.slug === slug);
}
