import type { PredictionMarket } from "@/generated/prisma/enums";

export type MarketFilter =
  | { type: "market"; markets: PredictionMarket[] }
  | { type: "oddsRange"; min: number; max: number }
  | { type: "all" }
  | { type: "banker" }
  | { type: "topConfidence"; minConfidence: number };

export type MarketPageConfig = {
  slug: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  filter: MarketFilter;
};

export const MARKET_PAGES: MarketPageConfig[] = [
  {
    slug: "1x2",
    h1: "1X2 Predictions",
    metaTitle: "1X2 Match Result Predictions Today",
    metaDescription: "Today's 1X2 (match result) tips - Home Win, Draw, or Away Win - generated by our statistical model.",
    intro:
      "The classic match result market: 1 for Home Win, X for Draw, 2 for Away Win. Our pick is whichever of the three the score matrix gives the highest probability, shown with its derived odds and a confidence figure.",
    filter: { type: "market", markets: ["HOME_WIN", "DRAW", "AWAY_WIN"] },
  },
  {
    slug: "over-1-5-goals",
    h1: "Over 1.5 Goals Predictions",
    metaTitle: "Over 1.5 Goals Predictions Today",
    metaDescription: "Today's Over 1.5 goals tips, generated by our statistical model.",
    intro:
      "Fixtures where our model expects at least two goals, based on both teams' scoring and conceding form. It's one of the lower-variance goals markets, so it usually carries shorter odds and higher confidence than Over 2.5.",
    filter: { type: "market", markets: ["OVER_1_5"] },
  },
  {
    slug: "over-2-5-goals",
    h1: "Over 2.5 Goals Predictions",
    metaTitle: "Over 2.5 Goals Predictions Today",
    metaDescription: "Today's Over 2.5 goals tips, generated by our statistical model.",
    intro:
      "Fixtures where our model expects three or more goals. It reads each side's recent attacking and defensive numbers, home and away weighted separately, to estimate the total.",
    filter: { type: "market", markets: ["OVER_2_5"] },
  },
  {
    slug: "under-3-5-goals",
    h1: "Under 3.5 Goals Predictions",
    metaTitle: "Under 3.5 Goals Predictions Today",
    metaDescription: "Today's Under 3.5 goals tips, generated by our statistical model.",
    intro:
      "Fixtures our model expects to stay under four total goals. It covers most low- and mid-scoring games and only misses when a match turns into a goal glut.",
    filter: { type: "market", markets: ["UNDER_3_5"] },
  },
  {
    slug: "both-teams-to-score",
    h1: "Both Teams to Score Predictions",
    metaTitle: "BTTS Predictions Today",
    metaDescription: "Today's Both Teams to Score (BTTS) tips, generated by our statistical model.",
    intro:
      "Fixtures where our model favours both sides finding the net. The estimate combines each team's chance of scoring with its chance of keeping a clean sheet, from recent form.",
    filter: { type: "market", markets: ["BTTS_YES", "BTTS_NO"] },
  },
  {
    slug: "double-chance",
    h1: "Double Chance Predictions",
    metaTitle: "Double Chance Predictions Today",
    metaDescription: "Today's Double Chance tips (1X, X2, 12), generated by our statistical model.",
    intro:
      "A lower-risk market covering two of the three possible results in one bet. Odds are shorter than a straight win, so these picks tend to sit at higher confidence.",
    filter: { type: "market", markets: ["DOUBLE_CHANCE_1X", "DOUBLE_CHANCE_X2", "DOUBLE_CHANCE_12"] },
  },
  {
    slug: "draw-no-bet",
    h1: "Draw No Bet Predictions",
    metaTitle: "Draw No Bet Predictions Today",
    metaDescription: "Today's Draw No Bet tips, generated by our statistical model.",
    intro:
      "Back a side to win with your stake refunded if the match ends level. It removes the draw as a losing outcome, which suits close games where our model leans one way but not strongly.",
    filter: { type: "market", markets: ["DRAW_NO_BET_HOME", "DRAW_NO_BET_AWAY"] },
  },
  {
    slug: "correct-score",
    h1: "Correct Score Predictions",
    metaTitle: "Correct Score Predictions Today",
    metaDescription: "Today's Correct Score tips - the model's highest-probability final scoreline per fixture.",
    intro:
      "Higher risk, higher reward - the single most likely final score from our score matrix. Even the top scoreline is usually well under 20% to land, so confidence here is always modest.",
    filter: { type: "market", markets: ["CORRECT_SCORE"] },
  },
  {
    slug: "home-wins",
    h1: "Home Win Predictions",
    metaTitle: "Home Win Predictions Today",
    metaDescription: "Today's Home Win tips, generated by our statistical model.",
    intro:
      "Fixtures our model favours the home side to win outright. Home advantage is modelled explicitly, so these are games where recent form and venue point the same way.",
    filter: { type: "market", markets: ["HOME_WIN"] },
  },
  {
    slug: "away-wins",
    h1: "Away Win Predictions",
    metaTitle: "Away Win Predictions Today",
    metaDescription: "Today's Away Win tips, generated by our statistical model.",
    intro:
      "Fixtures our model favours the away side to win outright. A pick here means the model rates the visitors clearly stronger, since it's pricing them against home advantage.",
    filter: { type: "market", markets: ["AWAY_WIN"] },
  },
  {
    slug: "draws",
    h1: "Draw Predictions",
    metaTitle: "Draw Predictions Today",
    metaDescription: "Today's Draw tips, generated by our statistical model.",
    intro:
      "Fixtures our model rates as more likely than not to end level. Draws are hard to call, so this list is usually short and the odds relatively long.",
    filter: { type: "market", markets: ["DRAW"] },
  },
  {
    slug: "win-either-half",
    h1: "Over 0.5 Goals in the First Half",
    metaTitle: "First Half Goals Predictions Today",
    metaDescription: "Today's first-half goals tips - fixtures our model expects to see a goal before half-time.",
    intro:
      "Our model doesn't yet price a dedicated \"win either half\" market, so this page shows the closest thing it does model: a goal scored before half-time.",
    filter: { type: "market", markets: ["HT_OVER_0_5"] },
  },
  {
    slug: "single-bets",
    h1: "Today's Single Bets",
    metaTitle: "Single Bet Predictions Today",
    metaDescription: "Every standalone tip published today, across all markets.",
    intro:
      "Every tip our model has published today, one match at a time - no accumulators. Each row links through to the full match analysis, the odds breakdown, and the head-to-head.",
    filter: { type: "all" },
  },
  {
    slug: "banker-of-the-day",
    h1: "Banker of the Day",
    metaTitle: "Banker of the Day Predictions",
    metaDescription: "Our highest-confidence single tip each day.",
    intro: "The single pick our model is most confident in, one per day. Confidence is capped at 92% - nothing is guaranteed.",
    filter: { type: "banker" },
  },
  {
    slug: "2-odds",
    h1: "2 Odds Predictions",
    metaTitle: "2 Odds Predictions Today",
    metaDescription: "Today's tips priced around 2.00 odds.",
    intro:
      "Published tips with derived odds between 1.80 and 2.20. Odds come from the model's own probability for the selection, not from a bookmaker.",
    filter: { type: "oddsRange", min: 1.8, max: 2.2 },
  },
  {
    slug: "3-odds",
    h1: "3 Odds Predictions",
    metaTitle: "3 Odds Predictions Today",
    metaDescription: "Today's tips priced around 3.00 odds.",
    intro:
      "Published tips with derived odds between 2.5 and 3.5. These are lower-confidence picks by definition - longer odds mean the model gives the outcome a smaller chance.",
    filter: { type: "oddsRange", min: 2.5, max: 3.5 },
  },
  {
    slug: "5-odds",
    h1: "5 Odds Predictions",
    metaTitle: "5 Odds Predictions Today",
    metaDescription: "Today's tips priced around 5.00 odds.",
    intro:
      "Published tips with derived odds between 4.0 and 6.0 - the longest-priced selections we publish. Treat the confidence figure, not the odds, as the guide to how strong a pick is.",
    filter: { type: "oddsRange", min: 4.0, max: 6.0 },
  },
  {
    slug: "acca-tips",
    h1: "Accumulator Tips",
    metaTitle: "Acca Tips Today",
    metaDescription: "Today's highest-confidence tips, suggested as accumulator legs.",
    intro: "Today's tips at 80% confidence or higher - a starting point for building your own accumulator. Combining selections multiplies risk, not just returns.",
    filter: { type: "topConfidence", minConfidence: 80 },
  },
];

export function getMarketPageConfig(slug: string): MarketPageConfig | undefined {
  return MARKET_PAGES.find((m) => m.slug === slug);
}
