import type { Metadata } from "next";
import Link from "next/link";
import { absoluteUrl, SITE_NAME } from "@/lib/seo";
import { CONTACT } from "@/lib/contact.config";
import { LegalPageShell, Section } from "@/components/layout/LegalPageShell";

const DESCRIPTION = `Terms and conditions for using ${SITE_NAME} - free predictions, VIP subscriptions, accounts, and acceptable use.`;

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: DESCRIPTION,
  alternates: { canonical: absoluteUrl("/terms") },
  openGraph: { title: `Terms & Conditions | ${SITE_NAME}`, description: DESCRIPTION, url: absoluteUrl("/terms") },
};

export default function TermsPage() {
  return (
    <LegalPageShell
      title="Terms & Conditions"
      intro={`By using ${SITE_NAME} you agree to these terms. If you do not agree, please don't use the site.`}
      updated="August 2026"
    >
      <Section heading="The service">
        <p>
          {SITE_NAME} publishes football predictions generated by a statistical model, a public results
          archive, and an optional paid VIP tier. Free content is provided as-is. We may change, pause, or
          remove any part of the service at any time.
        </p>
      </Section>

      <Section heading="No guaranteed results">
        <p>
          Predictions are estimates, not guarantees - see the{" "}
          <Link href="/disclaimer" className="text-brand-hover dark:text-brand-light underline">
            disclaimer
          </Link>
          . Nothing on this site is financial advice. Bets you place are your own responsibility.
        </p>
      </Section>

      <Section heading="Accounts">
        <p>
          You are responsible for keeping your login details secure and for everything that happens under
          your account. Provide accurate information when you register, keep it up to date, and do not
          share your account. We may suspend or close accounts that break these terms.
        </p>
      </Section>

      <Section heading="VIP subscriptions">
        <p>
          VIP access is sold as a fixed-length package (for example daily, weekly, or monthly). Payments
          are processed by Paystack; we do not store your card details. Access begins once payment is
          confirmed and runs for the package length. Because VIP content is delivered immediately and
          cannot be returned, fees are non-refundable once selections for your period have been sent,
          except where required by law. If you were charged in error or never received access, contact us
          and we will put it right.
        </p>
      </Section>

      <Section heading="Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 flex flex-col gap-1.5">
          <li>scrape, bulk-download, or republish our content or data</li>
          <li>resell, forward, or share VIP selections with non-subscribers</li>
          <li>attempt to disrupt, probe, or gain unauthorised access to the site</li>
          <li>use the site where betting or accessing this content is unlawful</li>
        </ul>
      </Section>

      <Section heading="Intellectual property">
        <p>
          The model, the site design, the written analysis, and the {SITE_NAME} name and wordmark belong
          to us. You may link to our pages and quote short extracts with attribution; anything more needs
          our permission.
        </p>
      </Section>

      <Section heading="Third-party channels">
        <p>
          We communicate through WhatsApp and Telegram. Those platforms have their own terms and privacy
          practices that we do not control.
        </p>
      </Section>

      <Section heading="Liability">
        <p>
          The service is provided without warranties of any kind. To the fullest extent permitted by law,
          {" "}{SITE_NAME} is not liable for betting losses or for any indirect or consequential loss
          arising from your use of the site.
        </p>
      </Section>

      <Section heading="Changes and governing law">
        <p>
          We may update these terms; the &quot;last updated&quot; date shows when. Continued use after a
          change means you accept it. These terms are governed by the laws of the Federal Republic of
          Nigeria.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Questions about these terms:{" "}
          <a href={CONTACT.email.href} className="text-brand-hover dark:text-brand-light underline">
            {CONTACT.email.address}
          </a>
          .
        </p>
      </Section>
    </LegalPageShell>
  );
}
