import Link from "next/link";
import { MARKET_PAGES } from "@/lib/markets.config";
import { SITE_NAME, SITE_NAME_PREFIX, SITE_NAME_SUFFIX } from "@/lib/seo";

const DAYS = [
  { label: "Monday", slug: "monday-predictions" },
  { label: "Tuesday", slug: "tuesday-predictions" },
  { label: "Wednesday", slug: "wednesday-predictions" },
  { label: "Thursday", slug: "thursday-predictions" },
  { label: "Friday", slug: "friday-predictions" },
  { label: "Saturday", slug: "saturday-predictions" },
  { label: "Sunday", slug: "sunday-predictions" },
];

const QUICK_MARKETS = MARKET_PAGES.slice(0, 6);

export function Footer() {
  return (
    <footer className="mt-auto bg-zinc-950 text-zinc-400">
      <div className="max-w-6xl mx-auto px-4 py-12">
        <div className="text-center mb-10">
          <div className="font-bold text-lg text-white">
            {SITE_NAME_PREFIX}<span className="text-secondary">{SITE_NAME_SUFFIX}</span>
          </div>
          <p className="text-sm max-w-md mx-auto mt-2">
            Statistical football predictions, match analysis, and a public results archive - built on a
            Poisson/Dixon-Coles goals model driven by each team&apos;s recent home and away form.
          </p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 gap-8 text-sm">
          <div>
            <h3 className="text-white font-semibold mb-3 border-l-2 border-brand pl-2">Predictions by Day</h3>
            <ul className="flex flex-col gap-2">
              {DAYS.map((d) => (
                <li key={d.slug}>
                  <Link href={`/${d.slug}`} className="hover:text-white transition-colors">
                    {d.label} Predictions
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h3 className="text-white font-semibold mb-3 border-l-2 border-brand pl-2">Popular Markets</h3>
            <ul className="flex flex-col gap-2">
              {QUICK_MARKETS.map((m) => (
                <li key={m.slug}>
                  <Link href={`/${m.slug}`} className="hover:text-white transition-colors">
                    {m.h1}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h3 className="text-white font-semibold mb-3 border-l-2 border-brand pl-2">Site</h3>
            <ul className="flex flex-col gap-2">
              <li>
                <Link href="/" className="hover:text-white transition-colors">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/leagues" className="hover:text-white transition-colors">
                  Leagues
                </Link>
              </li>
              <li>
                <Link href="/results" className="hover:text-white transition-colors">
                  Results Archive
                </Link>
              </li>
              <li>
                <Link href="/blog" className="hover:text-white transition-colors">
                  Blog
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-10 pt-6 border-t border-zinc-800 flex flex-col gap-3 text-xs">
          <p className="font-medium text-zinc-300">18+ Gamble Responsibly</p>
          <p>
            Predictions on this site are statistical estimates generated by our model, not guaranteed outcomes.
            Betting involves risk - never stake more than you can afford to lose. If you or someone you know has a
            gambling problem, help is available.
          </p>
          <p>
            &copy; {new Date().getFullYear()} {SITE_NAME}. Every published tip, win or loss, stays in our{" "}
            <Link href="/results" className="underline hover:text-white">
              public results archive
            </Link>
            .
          </p>
        </div>
      </div>
    </footer>
  );
}
