import Link from "next/link";
import { MARKET_PAGES } from "@/lib/markets.config";
import { SITE_NAME } from "@/lib/seo";
import { CONTACT } from "@/lib/contact.config";
import { FooterContact } from "./FooterContact";
import { Logo } from "./Logo";

const SOCIALS = [
  {
    label: "Follow us on X",
    href: CONTACT.x.href,
    icon: (
      <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
    ),
  },
  {
    label: "Join our Telegram channel",
    href: CONTACT.telegramChannel.href,
    icon: (
      <path d="M21.94 4.6l-3.02 14.26c-.23 1.01-.83 1.26-1.68.78l-4.64-3.42-2.24 2.16c-.25.25-.46.46-.94.46l.33-4.73L18.7 6.3c.37-.33-.08-.51-.58-.18L6.66 13.4l-4.66-1.46c-1.01-.32-1.03-1.01.21-1.5l18.22-7.02c.84-.31 1.58.2 1.31 1.47z" />
    ),
  },
];

const DAYS = [
  { label: "Monday", slug: "monday-predictions" },
  { label: "Tuesday", slug: "tuesday-predictions" },
  { label: "Wednesday", slug: "wednesday-predictions" },
  { label: "Thursday", slug: "thursday-predictions" },
  { label: "Friday", slug: "friday-predictions" },
  { label: "Saturday", slug: "saturday-predictions" },
  { label: "Sunday", slug: "sunday-predictions" },
];

const QUICK_LINKS = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About Us" },
  { href: "/vip", label: "VIP Packages" },
  { href: "/leagues", label: "Leagues" },
  { href: "/results", label: "Results Archive" },
  { href: "/blog", label: "Blog" },
];

const LEGAL_LINKS = [
  { href: "/disclaimer", label: "Disclaimer" },
  { href: "/terms", label: "Terms & Conditions" },
  { href: "/privacy", label: "Privacy Policy" },
];

const DAY_LINKS = DAYS.map((d) => ({ href: `/${d.slug}`, label: `${d.label} Predictions` }));

const MARKET_LINKS = MARKET_PAGES.slice(0, 6).map((m) => ({ href: `/${m.slug}`, label: m.h1 }));

const headingClass =
  "mb-3.5 border-l-2 border-secondary pl-2.5 font-mono text-[11px] font-semibold uppercase tracking-[0.14em] text-white";
const linkClass = "text-white/55 transition-colors hover:text-white";

function LinkColumn({ heading, links }: { heading: string; links: { href: string; label: string }[] }) {
  return (
    <div>
      <h3 className={headingClass}>{heading}</h3>
      <ul className="flex flex-col gap-2">
        {links.map((l) => (
          <li key={l.href + l.label}>
            <Link href={l.href} className={linkClass}>
              {l.label}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export function Footer() {
  return (
    <footer className="mt-auto border-t border-white/10 bg-[#08110D] text-white/55">
      <div className="mx-auto max-w-6xl px-4 py-14 sm:px-6">
        <div className="mb-12 text-center">
          <Link href="/" aria-label={`${SITE_NAME} home`} className="inline-block">
            <Logo className="mx-auto h-11 w-auto" />
          </Link>
          <p className="mx-auto mt-4 max-w-md text-sm leading-relaxed">
            Statistical football predictions, match analysis, and a public results archive &mdash; built on a
            Poisson/Dixon&ndash;Coles goals model driven by each team&apos;s recent home and away form.
          </p>
        </div>

        <div className="grid grid-cols-2 gap-8 text-sm md:grid-cols-4">
          <LinkColumn heading="Quick Links" links={QUICK_LINKS} />
          <LinkColumn heading="Legal Links" links={LEGAL_LINKS} />
          <LinkColumn heading="Predictions by Day" links={DAY_LINKS} />
          <LinkColumn heading="Popular Markets" links={MARKET_LINKS} />
        </div>

        <div className="mt-12 border-t border-white/10 pt-8 text-sm">
          <FooterContact />
        </div>

        <div className="mt-12 flex flex-col gap-3 border-t border-white/10 pt-8 text-xs">
          <div className="flex items-center gap-3">
            {SOCIALS.map((s) => (
              <a
                key={s.href}
                href={s.href}
                target="_blank"
                rel="noopener noreferrer"
                aria-label={s.label}
                className="flex h-9 w-9 items-center justify-center rounded-full border border-white/15 text-white/70 transition-colors hover:border-white/40 hover:text-white"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
                  {s.icon}
                </svg>
              </a>
            ))}
          </div>
          <p className="font-mono text-[11px] font-semibold uppercase tracking-[0.14em] text-white/80">
            18+ &middot; Gamble responsibly
          </p>
          <p className="leading-relaxed">
            Predictions on this site are statistical estimates generated by our model, not guaranteed outcomes.
            Betting involves risk - never stake more than you can afford to lose. If you or someone you know has a
            gambling problem, help is available.
          </p>
          <p>
            &copy; {new Date().getFullYear()} {SITE_NAME}. Every published tip, win or loss, stays in our{" "}
            <Link href="/results" className="underline hover:text-white">
              public results archive
            </Link>
            .
          </p>
        </div>
      </div>
    </footer>
  );
}
